"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ADVERTENCIA DE SEGURIDAD: ¡mantener en secreto la clave secreta utilizada en producción!
SECRET_KEY = os.environ.get('SECRET_KEY')

# ADVERTENCIA DE SEGURIDAD: ¡no ejecutar con la depuración activada en producción!
DEBUG = os.environ.get('DEBUG') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'menu',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'menu' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if os.environ.get('USE_SQLITE', 'False') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'restaurante_hotel'), 
            'USER': os.environ.get('DB_USER', 'root'),                 
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),    
            'HOST': 'localhost',            
            'PORT': '3306',                 
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar' # El idioma por defecto al entrar

TIME_ZONE = 'America/Argentina/Buenos_Aires'

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

USE_I18N = True

USE_TZ = True

USE_L10N = True

NUMBER_GROUPING = 3

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
CORS_ALLOW_ALL_ORIGINS = True

JAZZMIN_SETTINGS = {
    "site_title": "Gestor Las Marías",
    "site_header": "Las Marías",
    "site_brand": "Gestor Las Marías",
    "welcome_sign": "Bienvenido al Panel de Administración",
    "site_logo": "logo_fav.png",
    "site_icon": "logo_nav.png",
    "site_logo_classes": "img-circle",
    
    "language_chooser": True, 
}

JAZZMIN_UI_TWEAKS = {
    "theme": "lumen",                    # Un tema base muy limpio y claro
    "sidebar": "sidebar-dark-primary",   # El menú lateral será negro profundo
    "navbar": "navbar-white navbar-light",# La barra superior será blanca
    "accent": "accent-black",            # Los detalles al hacer clic serán negros
    "button_classes": {
        "primary": "btn-dark",           # Botones de guardar/añadir en negro
        "secondary": "btn-outline-dark", # Botones secundarios en blanco con borde negro
        "info": "btn-dark",
        "warning": "btn-dark",
        "danger": "btn-outline-dark",
        "success": "btn-dark",
    },
}

CORS_ALLOW_ALL_ORIGINS = True

LOGIN_REDIRECT_URL = '/control-gestionador-marias/'
LOGOUT_REDIRECT_URL = '/control-gestionador-marias/login/'

# ==========================================
# CONFIGURACIONES DE SEGURIDAD PARA PRODUCCIÓN
# ==========================================

# Evita que incrusten tu sitio en un iframe (protección Clickjacking)
X_FRAME_OPTIONS = 'DENY'

# Filtros de seguridad del navegador
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Protege las cookies para que solo viajen por HTTPS (PythonAnywhere te da HTTPS gratis)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Redirige todo el tráfico HTTP a HTTPS
SECURE_SSL_REDIRECT = not DEBUG

# CSRF_TRUSTED_ORIGINS = ['https://lasmariashotel.pythonanywhere.com']