"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)7)^w2yh16ku*xs7)eon5v_n#)qddaoz6au(zsc*w=8p-rxxz6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'menu',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'restaurante_hotel',    
        'USER': 'root',                 
        'PASSWORD': 'Mauuroot12',    
        'HOST': 'localhost',            
        'PORT': '3306',                 
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar' # El idioma por defecto al entrar

TIME_ZONE = 'America/Argentina/Buenos_Aires'

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

USE_I18N = True

USE_TZ = True

USE_L10N = True

NUMBER_GROUPING = 3

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
CORS_ALLOW_ALL_ORIGINS = True

JAZZMIN_SETTINGS = {
    "site_title": "Las Marías Admin",
    "site_header": "Las Marías",
    "site_brand": "Gestor Las Marías",
    "welcome_sign": "Bienvenido al Panel de Administración",
    
    # ¡Esta es la magia que muestra el menú desplegable de idiomas arriba a la derecha!
    "language_chooser": True, 
}

JAZZMIN_UI_TWEAKS = {
    "theme": "lumen",                    # Un tema base muy limpio y claro
    "sidebar": "sidebar-dark-primary",   # El menú lateral será negro profundo
    "navbar": "navbar-white navbar-light",# La barra superior será blanca
    "accent": "accent-black",            # Los detalles al hacer clic serán negros
    "button_classes": {
        "primary": "btn-dark",           # Botones de guardar/añadir en negro
        "secondary": "btn-outline-dark", # Botones secundarios en blanco con borde negro
        "info": "btn-dark",
        "warning": "btn-dark",
        "danger": "btn-outline-dark",
        "success": "btn-dark",
    },
}

CORS_ALLOW_ALL_ORIGINS = True