# Generated by Django 6.0.4 on 2026-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platillo',
            name='activo',
        ),
        migrations.AddField(
            model_name='platillo',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (Inglés)'),
        ),
        migrations.AddField(
            model_name='platillo',
            name='descripcion_pt',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (Portugués)'),
        ),
        migrations.AddField(
            model_name='platillo',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre (Inglés)'),
        ),
        migrations.AddField(
            model_name='platillo',
            name='nombre_pt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre (Portugués)'),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
