# Generated by Django 6.0.4 on 2026-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_platillo_activo_platillo_descripcion_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre (Inglés)'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre_pt',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre (Portugués)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
