# Generated by Django 6.0.4 on 2026-06-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_pedido_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre (Inglés)')),
                ('nombre_pt', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre (Portugués)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Adicionales',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas / Aclaraciones'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='adicionales',
            field=models.ManyToManyField(blank=True, related_name='detalles_pedidos', to='menu.adicional'),
        ),
    ]
