# Generated by Django 6.0.4 on 2026-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_adicional_pedido_notas_detallepedido_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='platillos_permitidos',
            field=models.ManyToManyField(blank=True, related_name='adicionales_disponibles', to='menu.platillo'),
        ),
    ]
